services:
  postgis:
    image: postgis/postgis:17-3.5
    ports:
      - 5432:5432
    volumes:
      - postgis:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  django:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      DJANGO_POSTGIS_DB: postgres
      DJANGO_POSTGIS_USER: postgres
      DJANGO_POSTGIS_PASSWORD: postgres
      DJANGO_POSTGIS_HOST: postgis
      DJANGO_POSTGIS_PORT: 5432

  redis:
    image: eqalpha/keydb
    ports:
      - 6379:6379
    restart: on-failure

volumes:
  postgis:
