services:
  vite:
    build:
      context: ./apps/www
      dockerfile: dockerfile
    command: sh -c "npm run dev -- --host --port 5173"
    ports:
      - target: 5173
        published: 5173
    volumes:
      - type: bind
        source: ./apps/www
        target: /app
    restart: on-failure

  docs:
    build:
      context: ./apps/docs
      dockerfile: dockerfile
    volumes:
      - type: bind
        source: ./apps/docs
        target: /app
    pull_policy: always
    command: sh -c "uv sync && . .venv/bin/activate && uvicorn main:app --reload --host 0.0.0.0 --port 8001"
    ports:
      - target: 8001
        published: 8001

  django:
    build:
      context: ./apps/api
      dockerfile: dockerfile
    command: sh -c "uv sync && . .venv/bin/activate && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - target: 8000
        published: 8000
    environment:
      DJANGO_POSTGIS_DB: postgres
      DJANGO_POSTGIS_USER: postgres
      DJANGO_POSTGIS_PASSWORD: postgres
      DJANGO_POSTGIS_HOST: postgis
      DJANGO_POSTGIS_PORT: 5432
    depends_on:
      postgis:
        condition: service_healthy

    #resolve problema do windows e se descomentar quebra no windows

    # volumes:
    #   - type: bind
    #     source: ./apps/api
    #     target: /app
    restart: on-failure

  postgis:
    image: postgis/postgis:17-3.5
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: postgis_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-postgres}",
          "-U",
          "${POSTGRES_USER:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgis_data:
