services:
  # TODO: só permitir o acesso pelo nginx e bloquear o acesso direto a porta, dessa forma o banco não fica exposto pra internet
  nginx:
    image: nginx:1.27-alpine-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./devops/nginx/conf.d:/etc/nginx/conf.d
      - ./devops/certbot/conf:/etc/letsencrypt
      - ./devops/certbot/www:/var/www/certbot
    restart: always

  certbot:
    image: certbot/certbot:v3.2.0
    volumes:
      - ./devops/certbot/conf:/etc/letsencrypt
      - ./devops/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"

  postgis:
    image: postgis/postgis:17-3.5
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  django:
    build:
      context: ./apps/api
      dockerfile: dockerfile
    ports:
      - 8000:8000
    command: gunicorn firetrack.wsgi --bind 0.0.0.0:8000
    depends_on:
      - postgis
      - nginx
    environment:
      DJANGO_DEBUG: false
      DJANGO_POSTGIS_DB: postgres
      DJANGO_POSTGIS_USER: postgres
      DJANGO_POSTGIS_PASSWORD: postgres
      DJANGO_POSTGIS_HOST: postgis
      DJANGO_POSTGIS_PORT: 5432
      DJANGO_ALLOWED_HOSTS: '["nocta-software-dsm.com"]'
      # TODO: customizar o DJANGO_SECRET_KEY, com algo tipo o ansible vault + playbook
    restart: on-failure

  docs:
    build:
      context: ./apps/docs
      dockerfile: dockerfile
    ports:
      - 8001:8001
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    restart: on-failure

volumes:
  postgis_data:
