services:
  vite:
    build:
      context: ./apps/www
      dockerfile: dockerfile
    env_file: .env
    volumes:
      # Toda vez que se roda um build, o diretório build/ dentro é deletado, isso gera um EBUSY quando lança um syscall rmdir, *SE* o diretório estiver mapeado a um volume.
      # Esse problema é resolvido montando um diretório fora do volume, assim o build/ pode ser deletado e evitar o consumo de disco excessivo já que todo build gera arquivos novos.
      - vite_build:/app/mnt:rw

  django:
    build:
      context: ./apps/api
      dockerfile: dockerfile
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn firetrack.wsgi --bind 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
      postgis:
        condition: service_healthy
      nginx:
        condition: service_started
    volumes:
      - django_static:/app/static:rw
    env_file: .env
    restart: always

  docs:
    build:
      context: ./apps/docs
      dockerfile: dockerfile
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8001"
    expose:
      - 8001
    depends_on:
      nginx:
        condition: service_started
    restart: always

  nginx:
    image: nginx:1.27-alpine-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - django_static:/usr/share/nginx/static:ro
      - vite_build:/usr/share/nginx/html:ro
      - ./devops/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./devops/certbot/www:/var/www/certbot:ro
      - ./devops/certbot/conf:/etc/letsencrypt:ro
    restart: always

  certbot:
    image: certbot/certbot:v3.2.0
    volumes:
      - ./devops/certbot/www:/var/www/certbot:rw
      - ./devops/certbot/conf:/etc/letsencrypt:rw
    # Renova o certificado a cada 12h
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait $${!};
      done;"
    restart: always

  postgis:
    image: postgis/postgis:17-3.5
    expose:
      - 5432
    volumes:
      - postgis_data:/var/lib/postgresql/data:rw
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgis_data:
  django_static:
  vite_build:
