services:
  postgis:
    image: postgis/postgis:17-3.5
    ports:
      - 5432:5432
    volumes:
      - postgis:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  redis:
    image: eqalpha/keydb
    ports:
      - 6379:6379
    restart: on-failure

volumes:
  postgis:
