services:
  nginx:
    image: nginx:1.27-alpine-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./devops/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./devops/certbot/www:/var/www/certbot:ro
      - ./devops/certbot/conf:/etc/letsencrypt:ro
    restart: always

  certbot:
    image: certbot/certbot:v3.2.0
    volumes:
      - ./devops/certbot/www:/var/www/certbot:rw
      - ./devops/certbot/conf:/etc/letsencrypt:rw
    # Renova o certificado a cada 12h
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait $${!};
      done;"

  postgis:
    image: postgis/postgis:17-3.5
    volumes:
      - postgis_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  # pra fazer funcionar vamo precisar de um container registry privado dentro do digital ocean: https://cloud.digitalocean.com/registry
  # ou entrar dentro da máquina e fazer um git clone, e um docker build, que é mais fácil.
  django:
    build:
      context: ./apps/api
      dockerfile: dockerfile
    # image: registry.digitalocean.com/firetrack:django
    command: gunicorn firetrack.wsgi --bind 127.0.0.1:8000
    depends_on:
      - postgis
      - nginx
    environment:
      DJANGO_DEBUG: false
      DJANGO_POSTGIS_DB: postgres
      DJANGO_POSTGIS_USER: postgres
      DJANGO_POSTGIS_PASSWORD: postgres
      DJANGO_POSTGIS_HOST: postgis
      DJANGO_POSTGIS_PORT: 5432
      DJANGO_ALLOWED_HOSTS: '["nocta-software-dsm.com"]'
      # TODO: customizar o DJANGO_SECRET_KEY, com algo tipo o ansible vault + playbook
    restart: on-failure

  docs:
    build:
      context: ./apps/docs
      dockerfile: dockerfile
    # image: registry.digitalocean.com/firetrack:docs
    command: uvicorn main:app --host 127.0.0.1 --port 8001
    restart: on-failure

volumes:
  postgis_data:
