from enum import Enum


class ProcessingEvents(Enum):
    START = "START"
    SELECT_BBOX = "SELECT_BBOX"
    SELECT_PERIOD = "SELECT_PERIOD"
    CONFIRM_PROCESSING_SCOPE = "CONFIRM_PROCESSING_SCOPE"
    START_VISUAL_ANALYSIS = "START_VISUAL_ANALYSIS"
    CONCLUDE_VISUAL_ANALYSIS = "CONCLUDE_VISUAL_ANALYSIS"
    