from enum import Enum


class ProcessingEvents(Enum):
    START = "START"
    SELECT_BBOX = "SELECT_BBOX"
    SELECT_PERIOD = "SELECT_PERIOD"
    CONFIRM_PROCESSING_SCOPE = "CONFIRM_PROCESSING_SCOPE"
    START_VISUAL_ANALYSIS = "START_VISUAL_ANALYSIS"
    CONCLUDE_VISUAL_ANALYSIS = "CONCLUDE_VISUAL_ANALYSIS"
    START_VALID_PAIRS_SEPARATION = "START_VALID_PAIRS_SEPARATION"
    CONCLUDE_VALID_PAIRS_SEPARATION = "CONCLUDE_VALID_PAIRS_SEPARATION"
    START_INDEX_CREATION = "START_INDEX_CREATION"
    CONCLUDE_INDEX_CREATION = "CONCLUDE_INDEX_CREATION"
    START_DIFFERENCE_IMAGE_CREATION = "START_DIFFERENCE_IMAGE_CREATION"
    CONCLUDE_DIFFERENCE_IMAGE_CREATION = "CONCLUDE_DIFFERENCE_IMAGE_CREATION"
    START_AI_CLASSIFICATION = "START_AI_CLASSIFICATION"
    CONCLUDE_AI_CLASSIFICATION = "CONCLUDE_AI_CLASSIFICATION"
    PUBLISH = "PUBLISH"