from enum import Enum


class ProcessingStates(Enum):
    IDLE = "IDLE"
    STARTED = "STARTED"
    AOI_SELECTED = "AOI_SELECTED"
    PERIOD_SELECTED = "PERIOD_SELECTED"
    READY_FOR_VISUAL_ANALYSIS = "READY_FOR_VISUAL_ANALYSIS"
    IN_VISUAL_ANALYSIS = "IN_VISUAL_ANALYSIS"
    READY_FOR_VALID_PAIR_SEPARATION = "READY_FOR_VALID_PAIR_SEPARATION"
    IN_VALID_PAIR_SEPARATION = "IN_VALID_PAIR_SEPARATION"
    READY_FOR_INDEXES_CREATION = "READY_FOR_INDEXES_CREATION"
    IN_INDEXES_CREATION = "IN_INDEXES_CREATION"
    READY_FOR_DIFFERENCE_IMAGE_CREATION = "READY_FOR_DIFFERENCE_IMAGE_CREATION"
    IN_DIFFERENCE_IMAGE_CREATION = "IN_DIFFERENCE_IMAGE_CREATION"
    READY_FOR_AI_CLASSIFICATION = "READY_FOR_AI_CLASSIFICATION"
    IN_AI_CLASSIFICATION = "IN_AI_CLASSIFICATION"
    READY_FOR_PUBLISH = "READY_FOR_PUBLISH"
    PUBLISHED = "PUBLISHED"
    ABORTED = "ABORTED"
    INTERRUPTED = "INTERRUPTED"
