openapi: "3.1.0"
info:
  title: Firetracker
  contact:
    email: otavio.abreu96@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8000
  - url: https://nocta-software-dsm.com/firetracker/api
tags:
  - name: cicatriz_queimadas
    description: Cria o processamento para a classificação de Cicatriz de Queimadas.
paths:
  /cicatriz_queimadas:
    get:
      tags:
        - cicatriz_queimadas
      summary: Retorna todos os processamentos de Cicatriz de Queimadas do usuário logado.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  # TODO: falta mais informações sobre o processamento
                  $ref: "#/components/schemas/CreateCicatrizQueimadas"

    post:
      tags:
        - cicatriz_queimadas
      summary: Cria e inicializa um processamento vazio de Cicatriz de Queimadas.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateCicatrizQueimadas"

  /cicatriz_queimadas/{process_id}/area_of_interest:
    patch:
      tags:
        - cicatriz_queimadas
      summary: Muda a Área de Interesse (Area of Interest) do processamento selecionado.
      parameters:
        - name: process_id
          in: path
          required: true
          schema:
            type: number
            example: 145438
      requestBody:
        description: The min_x, max_x, min_y and max_y.
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                format: float
              minItems: 4
              maxItems: 4
              example: [-123.123, 123.123, -45.123, 45.123]
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddProcessAoi"
        "400":
          description: Invalid input
        "404":
          description: Process not found

  /cicatriz_queimadas/{process_id}/periodo:
    patch:
      tags:
        - cicatriz_queimadas
      summary: Change a blank process period to the one given.
      parameters:
        - name: process_id
          in: path
          required: true
          schema:
            type: number
            example: 145438
      requestBody:
        description: The period in the isoformat.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                start_datetime:
                  type: string
                  format: isoformat
                  example: "2021-08-01T00:00:00Z"
                end_datetime:
                  type: string
                  format: isoformat
                  example: "2021-08-31T23:59:59Z"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddProcessAoi"
        "400":
          description: Invalid input
        "404":
          description: Process not found

  /cicatriz_queimadas/{process_id}/confirm:
    patch:
      tags:
        - cicatriz_queimadas
      summary: Confirm the given information and start the visual analysis phase.
      parameters:
        - name: process_id
          in: path
          required: true
          schema:
            type: number
            example: 145438
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmProcess"
        "400":
          description: Invalid input
        "404":
          description: Process not found

components:
  schemas:
    CreateCicatrizQueimadas:
      type: object
      properties:
        id:
          type: number
          example: 145438
        status:
          type: string
          description: Estado atual do processamento de classificação de cicatriz de queimadas.
          enum:
            - IDLE
            - ABORTED
            - INTERRUPTED
          example: STARTED

    AddProcessAoi:
      type: object
      properties:
        id:
          type: number
          example: 145438
        status:
          type: string
          description: The current status of the fire scar classification process.
          enum:
            - BBOX_SELECTED
            - ABORTED
            - INTERRUPTED
          example: BBOX_SELECTED

    AddProcessPeriod:
      type: object
      properties:
        id:
          type: number
          example: 145438
        status:
          type: string
          description: The current status of the fire scar classification process.
          enum:
            - PERIOD_SELECTED
            - ABORTED
            - INTERRUPTED
          example: PERIOD_SELECTED

    ConfirmProcess:
      type: object
      properties:
        id:
          type: number
          example: 145438
        status:
          type: string
          description: The current status of the fire scar classification process.
          enum:
            - READY_FOR_VISUAL_ANALYSIS
            - ABORTED
            - INTERRUPTED
          example: READY_FOR_VISUAL_ANALYSIS
