# Generated by Django 5.1.6 on 2025-06-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='regrowth_threshold',
            field=models.IntegerField(default=30, help_text='Número de dias para considerar um par de imagens'),
        ),
    ]
