# Generated by Django 5.1.6 on 2025-05-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fenomeno', '0002_alter_fenomeno_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_img', models.CharField(help_text='Identificador único do candidato (ex: CBERS_4_AWFI_DRD_20230102_172_111_L2)', max_length=100)),
                ('nir', models.URLField(help_text='Link para o arquivo da banda NIR')),
                ('red', models.URLField(help_text='Link para o arquivo da banda RED')),
                ('thumbnail', models.URLField(help_text='Link para o arquivo do thumbnail')),
                ('datetime', models.DateTimeField(help_text='Data e hora do fenômeno')),
                ('valido', models.BooleanField(blank=True, help_text='Indica se o candidato é válido ou não', null=True)),
                ('fenomeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='fenomeno.fenomeno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'fenomeno'), name='unique_candidato_id_fenomeno')],
            },
        ),
    ]
