# Generated by Django 5.1.6 on 2025-05-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
        ('fenomeno', '0002_alter_fenomeno_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidato',
            name='unique_candidato_id_fenomeno',
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('id_img', 'fenomeno'), name='unique_candidato_id_fenomeno'),
        ),
    ]
