# Generated by Django 5.1.6 on 2025-05-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_remove_candidato_unique_candidato_id_fenomeno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='valido',
            new_name='valid',
        ),
    ]
