# Generated by Django 5.1.6 on 2025-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_rename_valido_candidato_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='path',
            field=models.IntegerField(default=0, help_text='Órbita do satélite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='path_row',
            field=models.CharField(default=0, help_text="Combinação de path e row no formato 'path_row' (ex: 172_111)", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='row',
            field=models.IntegerField(default=0, help_text='Ponto do satélite'),
            preserve_default=False,
        ),
    ]
