# Generated by Django 5.1.6 on 2025-04-17 01:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fenomeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('started', 'Started'), ('product_selected', 'Product Selected'), ('timespan_selected', 'Timespan Selected'), ('aoi_selected', 'AOI Selected'), ('ready_for_visual_analysis', 'Ready for Visual Analysis'), ('in_visual_analysis', 'In Visual Analysis'), ('ready_for_valid_pair_separation', 'Ready for Valid Pair Separation'), ('in_valid_pair_separation', 'In Valid Pair Separation'), ('ready_for_indexes_creation', 'Ready for Indexes Creation'), ('in_indexes_creation', 'In Indexes Creation'), ('ready_for_difference_image_creation', 'Ready for Difference Image Creation'), ('in_difference_image_creation', 'In Difference Image Creation'), ('ready_for_ai_classification', 'Ready for AI Classification'), ('in_ai_classification', 'In AI Classification'), ('ready_for_publish', 'Ready for Publish'), ('published', 'Published'), ('error', 'Error'), ('aborted', 'Aborted')], default='idle', max_length=40)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('filter_start_date', models.DateField(blank=True, null=True)),
                ('filter_end_date', models.DateField(blank=True, null=True)),
                ('aoi', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Área de interesse (Bounding Box) no sistema WGS84', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenomenos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
