# Generated by Django 5.1.6 on 2025-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenomeno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenomeno',
            name='state',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Started', 'Started'), ('Product Selected', 'Product Selected'), ('Timespan Selected', 'Timespan Selected'), ('AOI Selected', 'AOI Selected'), ('Ready for Visual Analysis', 'Ready for Visual Analysis'), ('In Visual Analysis', 'In Visual Analysis'), ('Ready for Valid Pair Separation', 'Ready for Valid Pair Separation'), ('In Valid Pair Separation', 'In Valid Pair Separation'), ('Ready for Indexes Creation', 'Ready for Indexes Creation'), ('In Indexes Creation', 'In Indexes Creation'), ('Ready for Difference Image Creation', 'Ready for Difference Image Creation'), ('In Difference Image Creation', 'In Difference Image Creation'), ('Ready for AI Classification', 'Ready for AI Classification'), ('In AI Classification', 'In AI Classification'), ('Ready for Publish', 'Ready for Publish'), ('Published', 'Published'), ('Error', 'Error'), ('Aborted', 'Aborted')], default='Idle', max_length=40),
        ),
    ]
