# Generated by Django 5.1.6 on 2025-06-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0004_candidato_path_candidato_path_row_candidato_row'),
        ('fenomeno', '0002_alter_fenomeno_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_pos', to='candidatos.candidato')),
                ('candidato_pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_pre', to='candidatos.candidato')),
                ('fenomeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenomeno', to='fenomeno.fenomeno')),
            ],
        ),
    ]
