name: deploy

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_context: ./apps/www
            docker_image: joaoprocopio/firetrack:www
            docker_secrets_key: DOCKER_WWW_SECRETS

          - docker_context: ./apps/api
            docker_image: joaoprocopio/firetrack:api

          - docker_context: ./apps/docs
            docker_image: joaoprocopio/firetrack:docs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.docker_context }}
          tags: ${{ matrix.docker_image }}
          secrets: ${{ secrets[matrix.docker_secrets_key] }}
