name: deploy

on:
  pull_request:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_context: ./apps/www
            docker_image: joaoprocopio/firetrack:www
            docker_secrets: |
              VITE_API_URL=$VITE_API_URL
              VITE_MAPBOX_ACCESS_TOKEN=$VITE_MAPBOX_ACCESS_TOKEN

          - docker_context: ./apps/api
            docker_image: joaoprocopio/firetrack:api
            docker_secrets: ""

          - docker_context: ./apps/docs
            docker_image: joaoprocopio/firetrack:docs
            docker_secrets: |

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.docker_context }}
          tags: ${{ matrix.docker_image }}
          secrets: ${{ matrix.docker_secrets }}
