name: toggle

on:
  schedule:
    # https://crontab.guru/
    - cron: "0 22 * * 1-5" # Liga a máquina:    todo dia da semana entre Segunda e Sexta as 19h em GMT-3 São Paulo (ou 22h UTC)
    - cron: "0 02 * * 1-5" # Desliga a máquina: todo dia da semana entre Segunda e Sexta as 23h em GMT-3 São Paulo (ou 02h UTC)
  workflow_dispatch:
    inputs:
      toggle:
        description: Ligar ou desligar a máquina
        required: true
        type: choice
        options:
          - "on"
          - "off"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  toggle:
    runs-on: ubuntu-24.04

    steps:
      - name: Install DOCTL
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Turn on
        if: github.event.inputs.toggle == 'on' || github.event.schedule == '0 22 * * 1-5'
        run: doctl compute droplet-action power-on ${{ secrets.DIGITAL_OCEAN_DROPLET_ID }}

      - name: Turn off
        if: github.event.inputs.toggle == 'off' || github.event.schedule == '0 02 * * 1-5'
        run: doctl compute droplet-action power-off ${{ secrets.DIGITAL_OCEAN_DROPLET_ID }}
