name: toggle

on:
  schedule:
    # https://crontab.guru/
    - cron: "0 19 * * *" # Todo dia 22h UTC -> 19h GMT -3 (São Paulo)
    - cron: "0 02 * * *" # Todo dia 02h UTC -> 23h GMT -3 (São Paulo)
  workflow_dispatch:
    inputs:
      toggle:
        description: "Ligar ou desligar a máquina"
        required: true
        type: choice
        options:
          - "on"
          - "off"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  toggle:
    runs-on: ubuntu-24.04

    steps:
      - name: Install DOCTL
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Turn on
        if: github.event.inputs.toggle == 'on' || github.event.schedule == '0 19 * * *'
        run: doctl compute droplet-action power-on ${{ secrets.DIGITAL_OCEAN_DROPLET_ID }}

      - name: Turn off
        if: github.event.inputs.toggle == 'off' || github.event.schedule == '0 02 * * *'
        run: doctl compute droplet-action power-off ${{ secrets.DIGITAL_OCEAN_DROPLET_ID }}
